<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Backline Logistics</title>
        <meta name="description" content="Backline Logistics takes away the worry and risk of goods delivery. With the support of our experienced and professional logistics managers and drivers Backline Logistics makes it easy for you to do business anywhere in the UK.">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/manifest.json">
        <meta name="msapplication-TileColor" content="#00482d">
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
        <meta name="theme-color" content="#00482d">
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,900" rel="stylesheet"> 
        <style>

            /* File generated by shrinker.ch - DateTime: 2017-08-23, 13:22:35 */
html,body{height:100%;height:100%}html{font-size:100%}html,*{box-sizing:border-box}body{font-family:'Lato',sans-serif;color:#fff;margin:0;padding:0;font-size:1.2rem;background:#00482d;font-weight:100}.content{position:relative;z-index:1;height:100%;min-height:100%;width:100%;max-width:1300px;background:#00482d;display:inline-block}header{width:40%;min-width:280px;margin:0 auto}header img{width:100%;height:auto}.desktop-only{display:block}.mobile-only{display:none}.container{height:100%;margin:0 auto;min-height:100%;position:relative}main{padding-bottom:2rem}.one-third{display:inline-block;vertical-align:top;margin:.5rem 0}.social-link{display:inline-block;padding:0 .5rem;margin:.5rem 0}.social-link a{color:#52c549;text-decoration:none}.social-link a span{width:30px;height:30px;display:inline-block;background-size:contain;vertical-align:middle;margin-right:.5rem}.social-sharing{width:188px;margin:1rem auto 0 auto;background:#fff;position:relative}.social-sharing:after{content:'';display:block;position:absolute;top:50%;width:219%;height:1px;background:red;z-index:-1;left:50%;transform:translate(-50%);background:-moz-linear-gradient(left,rgba(254,252,234,0.01) 0,rgba(246,244,226,0.01) 1%,rgba(2,1,1,1) 30%,rgba(0,0,0,1) 51%,rgba(0,0,0,1) 70%,rgba(0,0,0,0.97) 71%,rgba(241,218,54,0) 100%);background:-webkit-linear-gradient(left,rgba(254,252,234,0.01) 0,rgba(246,244,226,0.01) 1%,rgba(2,1,1,1) 30%,rgba(0,0,0,1) 51%,rgba(0,0,0,1) 70%,rgba(0,0,0,0.97) 71%,rgba(241,218,54,0) 100%);background:linear-gradient(to right,rgba(254,252,234,0.01) 0,rgba(246,244,226,0.01) 1%,rgba(2,1,1,1) 30%,rgba(0,0,0,1) 51%,rgba(0,0,0,1) 70%,rgba(0,0,0,0.97) 71%,rgba(241,218,54,0) 100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#03fefcea',endColorstr='#00f1da36',GradientType=1)}.social-sharing .social-link a{display:inline-block;border-radius:50%;width:35px;height:35px;transition:all .6s ease}.social-sharing .social-link a:hover{transform:translatey(-.4rem)}span.email{background:url(<?php echo get_template_directory_uri();?>/assets/svg/email.svg);width:35px;height:35px;display:inline-block;background-size:contain;vertical-align:bottom;margin-right:.5rem}span.tel{background:url(<?php echo get_template_directory_uri();?>/assets/svg/phone.svg);width:35px;height:35px;display:inline-block;background-size:contain;vertical-align:bottom;margin-right:.5rem}span.twenty{background:url(<?php echo get_template_directory_uri();?>/assets/svg/twenty.svg);width:35px;height:35px;display:inline-block;background-size:contain;vertical-align:bottom;margin-right:.5rem}span.twitter{background:url(<?php echo get_template_directory_uri();?>/assets/svg/twitter.svg);width:30px;height:30px;display:inline-block;background-size:contain;vertical-align:bottom}span.facebook{background:url(<?php echo get_template_directory_uri();?>/assets/svg/facebook.svg);width:30px;height:30px;display:inline-block;background-size:contain;vertical-align:bottom}span.instagram{background:url(<?php echo get_template_directory_uri();?>/assets/svg/instagram.svg);width:30px;height:30px;display:inline-block;background-size:contain;vertical-align:bottom}address{font-style:normal}address p{font-weight:100;font-size:80%;color:rgba(255,255,255,.3)}svg{width:63%;display:block}.anim-slidein{animation-name:slidein;animation-duration:5s;animation-delay:.5s;animation-iteration-count:once;animation-fill-mode:forwards;opacity:0}@-webkit-keyframes slidein{0%{opacity:0}100%{opacity:1}}@keyframes slidein{0%{opacity:0}100%{opacity:1}}@media only screen and (min-width:768px){main{text-align:center}}@media only screen and (max-width:1199px){body{padding:4%}}@media only screen and (min-width:1200px){.container{overflow-y:hidden}.content{width:65%}.social-link{font-size:1.3rem}main{position:absolute;top:50%;-ms-transform:translatey(-50%);transform:translatey(-50%);font-weight:100;padding:0 3% 0 1%;text-align:center;padding-bottom:0}.aside{display:inline-block;height:100%;width:35%;top:0;background:url(<?php echo get_template_directory_uri();?>/assets/images/bg3.jpg);background-size:cover}.padding-right{padding:0 4rem 0 2rem}.aside{position:relative}.aside::before{content:'';display:block;position:absolute;top:-35%;left:-9%;width:22%;height:150%;background:#52bd48;transform:rotate(7deg);z-index:1}.aside::after{content:'';display:block;position:absolute;top:-35%;left:0;width:15%;height:150%;background:rgba(255,255,255,.8);transform:rotate(7deg);z-index:0}.one-third{margin:.5rem 0 .5rem 0}}@media only screen and (min-width:1400px){.content{width:60%}.aside{width:40%}}

        </style>
    </head>
    <body>
        
            <div class="container"><!--
             --><div class="content">
                   <main>
                        <header>
                        <img src="<?php echo get_template_directory_uri();?>/assets/images/backline-logo.jpg" alt="">
                        </header>
                        <div class="padding-right">
                        <p>Drawing on an impressive fleet of standard and specialised vehicles, trailers and mechanical handling equipment Backline Logistics takes away the worry and risk of goods delivery. With the support of our experienced and professional logistics managers and drivers Backline Logistics makes it easy for you to do business anywhere in the UK.</p>
                        <p style="font-weight: 100">Call us if you would like to know more about how Backline Logistics can help with all your logistics needs or are a top rate driver interested in joining our team.</p>
                        </div>
                        <div class="one-third">
                            <p class="social-link" style="display:inline-block;"><a href="mailto: traffic@backlinelogistics.co.uk" itemprop="email" ><span class="email"></span> traffic@backlinelogistics.co.uk</a></p>
                        </div><!--end one-third-->
                        <div class="one-third">
                            <p class="social-link" style="display:inline-block;"><a href="tel:01525 382 299" itemprop="telephone" ><span class="tel"></span>01525 382 299</a></p>
                        </div><!--end one-third-->
                        <div class="one-third">
                            <p class="social-link" style="display:inline-block;"><a href="tel:07799 761 654" itemprop="telephone" ><span class="twenty"></span>07799 761 654</a></p>
                        </div><!--end one-third-->
                        <div class="members-wrap">
                            <img src="<?php echo get_template_directory_uri();?>/assets/images/fta.png" alt="FTA Member" style="width: 56px;margin: .5rem 1rem;">
                            <img src="<?php echo get_template_directory_uri();?>/assets/images/rha.png" alt="RHA member" style="width:76px;margin: .5rem 1rem;">
                        </div><!--end members wrap-->
                         <address><p>Backline Logistics Ltd, Boss Avenue, Leighton Buzzard, Bedfordshire LU7 4SD</p></address>
                    </main>
                </div><!--
             --><div class="aside">
             </div>
         </div><!--end container-->

    </body>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-105179671-1', 'auto');
      ga('send', 'pageview');

    </script>
</html>
